### ISSUE TITLE
feedback, as requested on twitter :-)

### ISSUE THREAD

**Issue by sasa1977** [thestonefox/elixir_poolboy_example#1]
Looking good, compliments on nice work :-)

A few comments:

> Poolboy is an Erlang library maintained on GitHub so including it as a dependency is simply the case of adding it to the Mixfile

I'd also suggest to add the dependecy in the [applications list](https://github.com/thestonefox/elixir_poolboy_example/blob/master/mix.exs#L19). Otherwise, building an OTP release will fail. This is a common omission, so maybe it's a good occasion to add a hint about it in the readme as well :-)

> `:poolboy.transaction(:example_pool, fn(pid) -> :gen_server.call(pid, 5) end)`

I'd actually suggest to add a wrapper around `:gen_server.call` (aka an interface function) to the worker module. This is a common practice, and it decouples the clients from the communication protocol. So you could have something like:

``` elixir
defmodule ElixirPoolboyExample.Worker do
  def square(pid, x) do
    :gen_server.call(pid, 5)
  end

  # ...
end
```

And then you can just use `ElixirPoolboyExample.Worker.square(pid, x)` in the client.

> To run the Squarer.square function in parallel and in the background, it just needs to have the Poolboy transaction call spawned in a new process.
> This is ideal for tasks that are long running and need to be run in the background where the response is not required by the calling function.

`spawn` is fine for this simple example, but in production, it should probably never be used directly. Instead it's better to use `Task.async` or `Task.start_link` which will create an OTP compliant process. I actually don't think you need to extend your example, because it focuses on the `poolboy`, and it's better to leave the needless clutter out. However, maybe it's worth adding a passing note about it. Or not, I'm not sure about this myself :-)

> This commit shows how to ensure Poolboy waits infinitely for an available worker.

In my personal opinion, `:infinity` is (almost) always a bad idea. It can cause hangs, resource leaks, and deadlocks. Adding a finite timeout, even if it is large, ensures that client gives up at some point. It's not perfect, but it may keep the system afloat when overloaded.

**Comment by thestonefox** [comment]
Thanks for the comments, I've done some sneaky rebasing to make it look as if I always knew to include `poolboy` in the applications list :)

I've added a comment about using `:infinity` is bad practice and a large number is preferable.

I've also done a quick update to specify that Poolboy is available on Hex.pm rather than using the github repo (it wasn't available on hex at the the time of writing originally).

I'll do an additional commit that shows the refactoring of wrapping the `:gen_server.call` as this would be a nice addition to the tutorial to highlight the benefits of this cleaner code.

**Comment by sasa1977** [comment]
Nice!

> Thanks for the comments, I've done some sneaky rebasing to make it look as if I always knew to include poolboy in the applications list :)

Hahaha, I used to do that in my early GH days, but I stopped. Rebasing is probably not harmful in your case, since this is not a library, but I wouldn't advise it otherwise, because you may mess up other forks, and this project already has some forks.

A nice thing is that OSS on GitHub forced to make peace with my own mistakes and imperfections. It took a bit time to accept that, but these days I don't sweat anymore if my project history proves how ignorant I was :-) I just commit on top, and keep the history unchanged.

Props again for the nice work on this tutorial :-)

**Comment by thestonefox** [comment]
Yeah I totally agree with sneaky rebasing in open source projects with code that can get out of date. That's why I like the GitHub pull request mechanism so you have to raise pull requests on to your own repos to prevent sneaky rebasing :)

I like a good Git commit history to be a form of documentation of how the project has evolved.

But in this instance, I went against the grain! :)

Thanks again for your review, and thanks for the original blog post that inspired this tutorial!
